### ISSUE TITLE
Symbol update docs or scripts?

### ISSUE THREAD

**Issue by dflatline** [googleprojectzero/ktrw#4]
Hi! Thank you for the truly awesome work @bazad! 

I made @NewDwarf's comments from #1 into a branch: https://github.com/dflatline/ktrw/commits/iOS13.3. I successfully tested basic debugging on an iPhone 10,1 17C54 and checkra1n 0.9.5 with that branch.

I can make that into a PR if that saves you time but it's not my work. What a mess for the contribution policy :/

While I am here: do you use IDA+BinDiff to help update symbols automatically? Are people still porting symbols forward from the iOS 12 beta1 symbol leak in this way?

Are there other options that don't require IDA? Levin's joker/jtool2 didn't yield any of these symbols by default. I started toying with some yara plugins for Hopper but then @NewDwarf beat me to it, presumably by manual binary string match-and-check?

Can you provide suggestions to help update these symbol offsets for future iOS releases? I can go back to work on Hopper scripts, if that is even a worthwhile direction...

**Comment by bazad** [comment]
Ah, thanks for reminding me about @NewDwarf's changes! I can add them in to KTRW without you needing to create a PR.

Unfortunately I don't have a good means of porting symbols forward from 12.0b1. I'm not aware of any tools that have the complete set implemented, although jtool2 and iometa do a good job for certain symbols. For this project I've been doing it manually, since I expect this process to become obsolete once checkra1n supports loading arbitrary binaries to patch the system.

**Comment by bazad** [comment]
I just pushed parameters for iOS 13.3. Unfortunately I'm still seeing the same instability as on iOS 13.2.2.

**Comment by bazad** [comment]
The latest commit significantly reduces the number of parameters that KTRW needs to support a new iOS version: you only need to add a file to `ktrw_gdb_stub/kernel_symbols`, no need to update `ktrw_kext_loader` anymore as it is now unused.

This process is still not automated, but at least it should be easier. As always, feel free to request support for a specific version.
